### ISSUE TITLE
Configurar variables de entorno

### ISSUE THREAD

**Issue by AlvaroRGZ** [Teidesat/Fomalhaut#18]
Utilizar dotenv o algún plugin similar para definir las variables de entorno del proyecto.

Al menos, configurar las siguientes variables:

- API_URL
- API_PORT

Nota: en el caso de utilizar un archivo `.env` que contenga la definición de las variables de entorno, este también sería compatible con docker compose de la siguiente forma:

```yml
services:
  my-service:
    # ...
    env_file:
      - .env
    # ...
    ports:
      - ${API_PORT}:${API_PORT}
    # ...
```

Bloqueado por:
- Inactividad
